Feat/setup swagger
Ludogorie-Soft/reservations-platform-be pull request #4
Opened 2024-09-29 11:41 UTC by HristoSLV

Setup swagger UI

2024-10-01 10:38 UTC, ignatIgnatov approved these changes
Looks Good!

2024-10-01 19:40 UTC, emiliyank requested changes

2024-10-01 19:40 UTC, emiliyank commented on build.gradle
> +	//id "io.swagger.core.v3.swagger-gradle-plugin" version "2.2.24"
remove unused commented code

2024-10-01 19:40 UTC, emiliyank commented on build.gradle
> +	// https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
remove commented code

2024-10-02 12:06 UTC, HristoSLV commented on build.gradle
> +	// https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
removed commented code

2024-10-02 12:21 UTC, merged